version: '3.8'

services:
  nailsalon-club:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s 
    preview: {
      allowedHosts: [
        'localhost',
        '127.0.0.1', 
        '0.0.0.0',
        '.nailsalon.club', // Allow all subdomains of nailsalon.club
        'qw88sw8o08wc8okcog4oskos.nailsalon.club', // Specific Coolify domain
      ],
    } 